"""add column

Revision ID: 1d9b529dd54d
Revises: cfb7e22f0e4d
Create Date: 2022-10-14 01:54:09.576235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9b529dd54d'
down_revision = 'cfb7e22f0e4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
