"""add column

Revision ID: 5fb5c7e41f72
Revises: cac42fdcea35
Create Date: 2022-10-14 01:58:59.269058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fb5c7e41f72'
down_revision = 'cac42fdcea35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'name2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('name2', mysql.VARCHAR(length=16), nullable=False))
    # ### end Alembic commands ###
