"""add column

Revision ID: 79f885c7d86c
Revises: b16b862aca47
Create Date: 2022-10-14 01:59:46.034016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f885c7d86c'
down_revision = 'b16b862aca47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('name3', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'name3')
    # ### end Alembic commands ###
