"""add column

Revision ID: 881889e81d42
Revises: f22d6db25e7a
Create Date: 2022-10-14 02:25:48.749730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881889e81d42'
down_revision = 'f22d6db25e7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
