"""add column

Revision ID: cac42fdcea35
Revises: 1d9b529dd54d
Create Date: 2022-10-14 01:58:24.273130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac42fdcea35'
down_revision = '1d9b529dd54d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('name2', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('title_filmes', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['title_filmes'], ['filmes.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artists')
    op.drop_table('test')
    op.drop_table('filmes')
    # ### end Alembic commands ###
