"""add column

Revision ID: f22d6db25e7a
Revises: 79f885c7d86c
Create Date: 2022-10-14 02:00:30.879916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22d6db25e7a'
down_revision = '79f885c7d86c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('name4', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'name4')
    # ### end Alembic commands ###
